// examples/atc/react/src/panel-header.tsx
import { AtcLogo } from './atc-logo';
import { FeedBadge } from './feed-badge';

/** The chat panel's header: lettermark, Hashbrown credit and status chip. */
export function PanelHeader() {
  return (
    <div className="atc-panel-header">
      <span className="atc-logo">
        <AtcLogo height={15} />
      </span>
      <a
        className="atc-credit"
        href="https://hashbrown.dev"
        target="_blank"
        rel="noreferrer"
      >
        built with Hashbrown
      </a>
      <span className="atc-panel-header-status">
        <FeedBadge />
      </span>
    </div>
  );
}

// examples/atc/angular/src/app/panel-header.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { AtcLogo } from './atc-logo';
import { FeedBadge } from './feed-badge';

/** The chat panel's header: lettermark, Hashbrown credit and status chip. */
@Component({
  selector: 'atc-panel-header',
  imports: [AtcLogo, FeedBadge],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'atc-panel-header' },
  template: `
    <atc-logo [height]="15" />
    <a
      class="atc-credit"
      href="https://hashbrown.dev"
      target="_blank"
      rel="noreferrer"
      >built with Hashbrown</a
    >
    <atc-feed-badge class="atc-panel-header-status" />
  `,
})
export class PanelHeader {}
