// samples/langchain/next/src/components/chat/Chat.tsx
import { type Chat as HashbrownChat } from '@hashbrownai/core';
import { useUiChat } from '@hashbrownai/react';
import { ReactElement, useCallback } from 'react';
import styles from './Chat.module.css';
import ChatInput from './ChatInput';
import {
  type RemoteAgentMessage,
  type RenderToolCall,
} from './Message';
import Messages from './Messages';
import { type Step } from './Steps';

interface ChatProps {
  agent: ReturnType<typeof useUiChat<HashbrownChat.AnyTool>>;
  isRunning?: boolean;
  onStop?: () => void;
  remoteAgentIsRunning?: boolean;
  remoteAgentSteps?: Step[];
  remoteAgentMessages?: RemoteAgentMessage[];
  renderToolCall?: RenderToolCall;
}

function Chat({
  agent,
  isRunning,
  onStop,
  remoteAgentIsRunning,
  remoteAgentSteps,
  remoteAgentMessages,
  renderToolCall,
}: ChatProps): ReactElement {
  const onSubmit = useCallback(
    (content: string) => {
      agent.sendMessage({ role: 'user', content });
    },
    [agent],
  );

  return (
    <div className={styles.container}>
      <Messages
        messages={agent.messages}
        remoteAgentIsRunning={remoteAgentIsRunning}
        steps={remoteAgentSteps}
        remoteAgentMessages={remoteAgentMessages}
        renderToolCall={renderToolCall}
      />
      <ChatInput isRunning={isRunning} onSubmit={onSubmit} onStop={onStop} />
    </div>
  );
}

Chat.displayName = 'Chat';

export default Chat;

// samples/langchain/angular/src/app/components/chat/chat.component.ts
import { Component, input, output } from '@angular/core';
import { UiChatResourceRef } from '@hashbrownai/angular';
import { type Chat as HashbrownChat } from '@hashbrownai/core';
import { Step } from '../../services/langgraph.service';
import { ChatInputComponent } from './chat-input.component';
import { MessagesComponent } from './messages.component';

@Component({
  selector: 'app-chat',
  imports: [MessagesComponent, ChatInputComponent],
  template: `
    <app-messages
      [messages]="agent().value()"
      [remoteAgentIsRunning]="remoteAgentIsRunning()"
      [steps]="remoteAgentSteps()"
    />
    <app-chat-input
      [isRunning]="isRunning()"
      (submitted)="onSubmit($event)"
      (stopped)="onStop()"
    />
  `,
  styles: `
    :host {
      height: 100%;
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: stretch;
      gap: 16px;
      padding: 16px;
      background-color: #f0f0f0;
      border-radius: 16px;
    }
  `,
})
export class ChatComponent {
  readonly agent = input.required<UiChatResourceRef<HashbrownChat.AnyTool>>();
  readonly isRunning = input(false);
  readonly remoteAgentIsRunning = input(false);
  readonly remoteAgentSteps = input<Step[]>([]);
  readonly stopped = output<void>();

  protected onSubmit(content: string): void {
    this.agent().sendMessage({ role: 'user', content });
  }

  protected onStop(): void {
    this.stopped.emit();
  }
}

export default ChatComponent;
