// samples/langchain/next/src/components/chat/Message.tsx
'use client';

import { ToolMessage } from '@ag-ui/client';
import { useAgent, useRenderToolCall } from '@copilotkitnext/react';
import { type Chat } from '@hashbrownai/core';
import {
  UiAssistantMessage,
  UiChatMessage,
  UiUserMessage,
} from '@hashbrownai/react';
import { useMemo } from 'react';
import MagicTextRenderer from './MagicTextRenderer';
import styles from './Message.module.css';

interface MessageProps {
  message: UiChatMessage<Chat.AnyTool>;
}

function isUser(
  message: UiChatMessage<Chat.AnyTool>,
): message is UiUserMessage {
  return message.role === 'user';
}

function isAssistant(
  message: UiChatMessage<Chat.AnyTool>,
): message is UiAssistantMessage<Chat.AnyTool> {
  return message.role === 'assistant';
}

function AssistantMessage({
  message,
}: {
  message: UiAssistantMessage<Chat.AnyTool>;
}) {
  const { agent: researchPlanAgent } = useAgent({ agentId: 'plan' });
  const renderToolCall = useRenderToolCall();

  const lastAssistantMessage = useMemo(
    () => researchPlanAgent.messages.findLast((m) => m.role === 'assistant'),
    [researchPlanAgent.messages],
  );

  const toolMessages = useMemo(
    () =>
      researchPlanAgent.messages.filter(
        (m): m is ToolMessage => m.role === 'tool',
      ),
    [researchPlanAgent.messages],
  );

  return (
    <div className={`${styles.message} ${styles.messageAssistant}`}>
      {message.ui}
      {lastAssistantMessage?.toolCalls?.map((toolCall) => {
        const toolMessage = toolMessages.find(
          (m) => m.toolCallId === toolCall.id,
        );
        return renderToolCall({
          toolCall,
          toolMessage,
        });
      })}
    </div>
  );
}

function UserMessage({ message }: { message: UiUserMessage }) {
  if (
    typeof message.content === 'string' &&
    message.content.trim().length > 0
  ) {
    return (
      <div className={`${styles.message} ${styles.messageUser}`}>
        <MagicTextRenderer
          text={message.content}
          unit="word"
          fragmentDuration={500}
        />
      </div>
    );
  }

  return null;
}

function Message({ message }: MessageProps) {
  const onLeft = isAssistant(message);

  if (!isUser(message) && !isAssistant(message)) {
    return null;
  }

  return (
    <div
      className={`${styles.container} ${
        onLeft ? styles.containerLeft : styles.containerRight
      }`}
    >
      {isUser(message) && <UserMessage message={message} />}
      {isAssistant(message) && <AssistantMessage message={message} />}
    </div>
  );
}

Message.displayName = 'Message';

export default Message;

// samples/langchain/angular/src/app/components/chat/message.component.ts
import { Component, computed, input } from '@angular/core';
import {
  MagicText,
  RenderMessageComponent,
  UiAssistantMessage,
  UiChatMessage,
  UiUserMessage,
} from '@hashbrownai/angular';
import { type Chat } from '@hashbrownai/core';

function isUser(
  message: UiChatMessage<Chat.AnyTool>,
): message is UiUserMessage {
  return message.role === 'user';
}

function isAssistant(
  message: UiChatMessage<Chat.AnyTool>,
): message is UiAssistantMessage<Chat.AnyTool> {
  return message.role === 'assistant';
}

@Component({
  selector: 'app-message',
  imports: [RenderMessageComponent, MagicText],
  template: `
    @if (isUser(message())) {
      @if (userText().trim().length) {
        <div class="container containerRight">
          <div class="message messageUser">
            <hb-magic-text [text]="userText()" />
          </div>
        </div>
      }
    } @else if (isAssistant(message())) {
      <div class="container containerLeft">
        <div class="message messageAssistant">
          <hb-render-message [message]="assistantMessage()!" />
        </div>
      </div>
    }
  `,
  styles: `
    .container {
      display: flex;
      width: 100%;
    }

    .containerLeft {
      justify-content: flex-start;
    }

    .containerRight {
      justify-content: flex-end;
    }

    .message {
      padding: 8px;
      border-radius: 8px;
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .messageAssistant {
      color: var(--gray-dark, rgba(61, 60, 58, 1));
    }

    .messageUser {
      background-color: rgba(251, 187, 82, 0.8);
      color: rgba(61, 60, 58, 1);
    }
  `,
})
export class MessageComponent {
  readonly message = input.required<UiChatMessage<Chat.AnyTool>>();

  protected readonly isUser = isUser;
  protected readonly isAssistant = isAssistant;

  protected readonly assistantMessage = computed(() => {
    const value = this.message();
    return isAssistant(value) ? value : null;
  });

  protected readonly userText = computed(() => {
    const value = this.message();
    return typeof value.content === 'string' ? value.content : '';
  });
}
