// examples/atc/react/src/components/arrivals-board.tsx
import {
  type AirportCode,
  arrivalsRows,
  boardShowsEta,
  plainLabel,
} from '@atc/shared';
import type { ComponentFallbackProps } from '@hashbrownai/core';
import { useAtcState, useAtcStore } from '../store';
import { CardSkeleton } from './card-skeleton';

/** Props the model provides. Rows stream in; each ID arrives whole. */
export interface ArrivalsBoardProps {
  readonly title: string;
  readonly airport: AirportCode;
  readonly hexes: string[];
}

/**
 * A live table of aircraft approaching or near an airport. The type sits
 * under each label; units are in the headers. The ETA column shows only when
 * one of them is approaching. Picking a live row shows that plane on the map.
 */
export function ArrivalsBoard({ title, airport, hexes }: ArrivalsBoardProps) {
  const store = useAtcStore();
  const state = useAtcState();
  const rows = arrivalsRows(state, airport, hexes);
  const showEta = boardShowsEta(state, airport, hexes);

  return (
    <section className="atc-card" data-testid="arrivals-board">
      <h3 className="atc-card-title">{plainLabel(title)}</h3>
      <table className="atc-board">
        <thead>
          <tr>
            <th scope="col">Flight</th>
            <th scope="col">Alt (ft)</th>
            <th scope="col">Dist (nm)</th>
            {showEta ? <th scope="col">ETA (min)</th> : null}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, index) => (
            <tr
              key={`${index}-${row.hex}`}
              data-testid="arrivals-row"
              data-hex={row.hex}
              data-status={row.status}
              className={
                [
                  row.selectable ? 'is-selectable' : '',
                  row.selected ? 'is-selected' : '',
                ]
                  .filter(Boolean)
                  .join(' ') || undefined
              }
              // The row's button bubbles here; clicks elsewhere in it count too.
              onClick={() => {
                if (row.selectable) store.revealAircraft(row.hex);
              }}
            >
              <td className="atc-board-flight">
                {row.selectable ? (
                  <button type="button" className="atc-pick">
                    <span className="atc-callsign">{row.label}</span>{' '}
                    <span className="atc-board-type">{row.aircraftType}</span>
                  </button>
                ) : (
                  <>
                    <span className="atc-callsign">{row.label}</span>{' '}
                    <span className="atc-board-type">
                      {row.aircraftType}
                      {row.status === 'out-of-range' ? ' · out of range' : null}
                    </span>
                  </>
                )}
              </td>
              <td>{row.altitude}</td>
              <td>{row.distance}</td>
              {showEta ? <td>{row.eta}</td> : null}
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}

/** Shown until the airport is known. */
export function ArrivalsBoardFallback({
  partialProps,
}: ComponentFallbackProps) {
  const title = partialProps?.['title'];

  return (
    <section className="atc-card" data-testid="arrivals-board-fallback">
      {typeof title === 'string' && title ? (
        <h3 className="atc-card-title">{plainLabel(title)}</h3>
      ) : null}
      <CardSkeleton />
    </section>
  );
}

// examples/atc/angular/src/app/components/arrivals-board.ts
import {
  type AirportCode,
  type ArrivalsRow,
  arrivalsRows,
  boardShowsEta,
  plainLabel,
} from '@atc/shared';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import type { JsonResolvedValue } from '@hashbrownai/core';
import { ATC_STORE, injectAtcState } from '../store';
import { CardSkeleton } from './card-skeleton';

/**
 * A live table of aircraft approaching or near an airport. The type sits
 * under each label; units are in the headers. The ETA column shows only when
 * one of them is approaching. Picking a live row shows that plane on the map.
 */
@Component({
  selector: 'atc-arrivals-board',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="atc-card" data-testid="arrivals-board">
      <h3 class="atc-card-title">{{ label() }}</h3>
      <table class="atc-board">
        <thead>
          <tr>
            <th scope="col">Flight</th>
            <th scope="col">Alt (ft)</th>
            <th scope="col">Dist (nm)</th>
            @if (showEta()) {
              <th scope="col">ETA (min)</th>
            }
          </tr>
        </thead>
        <tbody>
          @for (row of rows(); track $index) {
            <tr
              data-testid="arrivals-row"
              [attr.data-hex]="row.hex"
              [attr.data-status]="row.status"
              [class.is-selectable]="row.selectable"
              [class.is-selected]="row.selected"
              (click)="pick(row)"
            >
              <td class="atc-board-flight">
                @if (row.selectable) {
                  <button type="button" class="atc-pick">
                    <span class="atc-callsign">{{ row.label }}</span
                    >&ngsp;
                    <span class="atc-board-type">{{ row.aircraftType }}</span>
                  </button>
                } @else {
                  <span class="atc-callsign">{{ row.label }}</span
                  >&ngsp;
                  <span class="atc-board-type">
                    {{ row.aircraftType }}
                    @if (row.status === 'out-of-range') {
                      · out of range
                    }
                  </span>
                }
              </td>
              <td>{{ row.altitude }}</td>
              <td>{{ row.distance }}</td>
              @if (showEta()) {
                <td>{{ row.eta }}</td>
              }
            </tr>
          }
        </tbody>
      </table>
    </section>
  `,
})
export class ArrivalsBoard {
  readonly title = input.required<string>();
  readonly airport = input.required<AirportCode>();
  readonly hexes = input.required<string[]>();
  private readonly store = inject(ATC_STORE);
  private readonly state = injectAtcState();
  protected readonly label = computed(() => plainLabel(this.title()));
  protected readonly rows = computed(() =>
    arrivalsRows(this.state(), this.airport(), this.hexes()),
  );
  protected readonly showEta = computed(() =>
    boardShowsEta(this.state(), this.airport(), this.hexes()),
  );

  /** Shows a live row's plane on the map (the row's button bubbles here). */
  protected pick(row: ArrivalsRow): void {
    if (row.selectable) {
      this.store.revealAircraft(row.hex);
    }
  }
}

/** Shown until the airport is known. */
@Component({
  selector: 'atc-arrivals-board-fallback',
  imports: [CardSkeleton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="atc-card" data-testid="arrivals-board-fallback">
      @if (title()) {
        <h3 class="atc-card-title">{{ title() }}</h3>
      }
      <atc-card-skeleton />
    </section>
  `,
})
export class ArrivalsBoardFallback {
  readonly partialProps = input<Record<string, JsonResolvedValue>>({});
  protected readonly title = computed(() => {
    const title = this.partialProps()['title'];

    return typeof title === 'string' ? plainLabel(title) : '';
  });
}
