// examples/atc/react/src/components/flight-card.tsx
import { flightCardView } from '@atc/shared';
import type { ComponentFallbackProps } from '@hashbrownai/core';
import { useEffect } from 'react';
import { useAtcState, useAtcStore } from '../store';
import { CardSkeleton } from './card-skeleton';

/** Props the model provides. `hex` arrives whole; `note` streams. */
export interface FlightCardProps {
  readonly note: string;
  readonly hex: string;
}

/**
 * One aircraft. Reads live data from the store, so it keeps updating after
 * the answer ends. Its header shows the plane on the map.
 */
export function FlightCard({ note, hex }: FlightCardProps) {
  const store = useAtcStore();
  const view = flightCardView(useAtcState(), hex);
  useEffect(() => store.pulse(hex), [store, hex]);

  if (view.status === 'unknown') {
    return (
      <article
        className="atc-card"
        data-testid="flight-card"
        data-hex={view.hex}
        data-status="unknown"
      >
        <p className="atc-card-title">Unknown aircraft</p>
        <p className="atc-card-note">{note}</p>
      </article>
    );
  }

  return (
    <article
      className="atc-card"
      data-testid="flight-card"
      data-hex={view.hex}
      data-status={view.status}
    >
      <header>
        <button
          type="button"
          className={`atc-pick${view.selected ? ' is-selected' : ''}`}
          disabled={view.status !== 'live'}
          onClick={() => store.revealAircraft(view.hex)}
        >
          <strong className="atc-callsign">{view.label}</strong>
          {view.subtitle ? (
            <span className="atc-card-muted">{view.subtitle}</span>
          ) : null}
        </button>
      </header>
      <p className="atc-card-muted">
        {view.aircraftType}
        {view.route ? ` · ${view.route}` : null}
      </p>
      <dl>
        <div>
          <dt>Altitude</dt>
          <dd data-testid="flight-altitude">{view.altitude}</dd>
        </div>
        <div>
          <dt>Speed</dt>
          <dd>{view.speed}</dd>
        </div>
        <div>
          <dt>Heading</dt>
          <dd>{view.heading}</dd>
        </div>
      </dl>
      {view.lastSeen ? (
        <p className="atc-card-muted">
          Out of range · last seen {view.lastSeen}
        </p>
      ) : null}
      <p className="atc-card-note">{note}</p>
    </article>
  );
}

/** Shown until the full aircraft ID has arrived. */
export function FlightCardFallback({ partialProps }: ComponentFallbackProps) {
  const note = partialProps?.['note'];

  return (
    <article className="atc-card" data-testid="flight-card-fallback">
      <CardSkeleton />
      {typeof note === 'string' && note ? (
        <p className="atc-card-note">{note}</p>
      ) : null}
    </article>
  );
}

// examples/atc/angular/src/app/components/flight-card.ts
import { flightCardView } from '@atc/shared';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  type OnInit,
} from '@angular/core';
import type { JsonResolvedValue } from '@hashbrownai/core';
import { ATC_STORE, injectAtcState } from '../store';
import { CardSkeleton } from './card-skeleton';

/**
 * One aircraft. Reads live data from the store, so it keeps updating after
 * the answer ends. Its header shows the plane on the map.
 */
@Component({
  selector: 'atc-flight-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let card = view();
    @if (card.status === 'unknown') {
      <article
        class="atc-card"
        data-testid="flight-card"
        [attr.data-hex]="card.hex"
        data-status="unknown"
      >
        <p class="atc-card-title">Unknown aircraft</p>
        <p class="atc-card-note">{{ note() }}</p>
      </article>
    } @else {
      <article
        class="atc-card"
        data-testid="flight-card"
        [attr.data-hex]="card.hex"
        [attr.data-status]="card.status"
      >
        <header>
          <button
            type="button"
            class="atc-pick"
            [class.is-selected]="card.selected"
            [disabled]="card.status !== 'live'"
            (click)="store.revealAircraft(card.hex)"
          >
            <strong class="atc-callsign">{{ card.label }}</strong>
            @if (card.subtitle) {
              <span class="atc-card-muted">{{ card.subtitle }}</span>
            }
          </button>
        </header>
        <p class="atc-card-muted">
          {{ card.aircraftType }}
          @if (card.route) {
            · {{ card.route }}
          }
        </p>
        <dl>
          <div>
            <dt>Altitude</dt>
            <dd data-testid="flight-altitude">{{ card.altitude }}</dd>
          </div>
          <div>
            <dt>Speed</dt>
            <dd>{{ card.speed }}</dd>
          </div>
          <div>
            <dt>Heading</dt>
            <dd>{{ card.heading }}</dd>
          </div>
        </dl>
        @if (card.lastSeen) {
          <p class="atc-card-muted">
            Out of range · last seen {{ card.lastSeen }}
          </p>
        }
        <p class="atc-card-note">{{ note() }}</p>
      </article>
    }
  `,
})
export class FlightCard implements OnInit {
  readonly note = input.required<string>();
  readonly hex = input.required<string>();
  protected readonly store = inject(ATC_STORE);
  private readonly state = injectAtcState();
  protected readonly view = computed(() =>
    flightCardView(this.state(), this.hex()),
  );

  ngOnInit(): void {
    this.store.pulse(this.hex());
  }
}

/** Shown until the full aircraft ID has arrived. */
@Component({
  selector: 'atc-flight-card-fallback',
  imports: [CardSkeleton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <article class="atc-card" data-testid="flight-card-fallback">
      <atc-card-skeleton />
      @if (note()) {
        <p class="atc-card-note">{{ note() }}</p>
      }
    </article>
  `,
})
export class FlightCardFallback {
  readonly partialProps = input<Record<string, JsonResolvedValue>>({});
  protected readonly note = computed(() => {
    const note = this.partialProps()['note'];

    return typeof note === 'string' ? note : '';
  });
}
