// www/src/app/examples/angular/chat/src/app/app.component.ts
import { Component, inject, resource } from '@angular/core';
import {
  createTool,
  createToolWithArgs,
  uiChatResource,
} from '@hashbrownai/angular';
import { exposeComponent, s } from '@hashbrownai/core';
import { CardComponent } from './components/card.component';
import { ComposerComponent } from './components/composer.component';
import { ConfigComponent } from './components/config.component';
import { LightComponent } from './components/light.component';
import { MarkdownComponent } from './components/markdown.component';
import { MessagesComponent } from './components/messages.component';
import { Light } from './models/light';
import { AuthService } from './services/auth.service';
import { LightsStore } from './store/lights.store';

@Component({
  selector: 'app-root',
  imports: [
    ComposerComponent,
    ConfigComponent,
    LightComponent,
    MessagesComponent,
  ],
  providers: [LightsStore],
  template: `
    <div class="app">
      <app-config />
      <div class="lights">
        <h3>Lights</h3>
        @for (light of lightsResource.value(); track light.id) {
          <button>
            <app-light [lightId]="light.id" (change)="onChange($event)" />
          </button>
        }
      </div>
      <div class="chat">
        <app-messages [messages]="chat.value()" />
        <app-composer (sendMessage)="sendMessage($event)"></app-composer>
      </div>
    </div>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      gap: 16px;
      background: rgba(61, 60, 58, 0.08);
      height: 100%;
    }

    .app {
      flex: 1 auto;
      display: grid;
      grid-template-columns: 1fr;
      grid-template-rows: auto 1fr 2fr;
      height: 100%;
      gap: 16px;
      padding: 16px;
    }

    .lights {
      display: flex;
      flex-direction: column;
      align-items: stretch;
      gap: 16px;
      padding: 16px;
      background: #fff;
      border-radius: 12px;
      overflow-y: auto;

      > h3 {
        color: rgba(61, 60, 58, 0.88);
        font: 600 12px/18px sans-serif;
        text-transform: uppercase;
      }
    }

    .chat {
      display: flex;
      flex-direction: column;
      align-items: stretch;
      gap: 16px;
      padding: 16px;
      background: #fff;
      border-radius: 12px;
      height: 100%;
      grid-row: 3;
      overflow: hidden;
    }

    @media screen and (min-width: 768px) {
      .app {
        grid-template-columns: 320px 1fr;
        grid-template-rows: auto auto;

        > app-config {
          grid-column: 1 / span 2;
          grid-row: 1;
        }

        > .lights {
          grid-column: 1;
          grid-row: 2;
        }

        .chat {
          grid-column: 2;
          grid-row: 2;
        }
      }

      .lights {
        max-height: inherit;
      }
    }

    @media screen and (min-width: 1024px) {
      .app {
        grid-template-columns: 400px auto;
      }
    }
  `,
})
export class App {
  lightsStore = inject(LightsStore);

  chat = uiChatResource({
    model: 'gpt-4.1',
    debugName: 'lights-chat',
    prompt:
      'You are a helpful assistant that can answer questions and help with tasks',
    components: [
      exposeComponent(MarkdownComponent, {
        name: 'markdown',
        description: 'Show markdown to the user',
        props: {
          data: s.streaming.string('The markdown content'),
        },
      }),
      exposeComponent(LightComponent, {
        name: 'light',
        description: 'Show a light to the user',
        props: {
          lightId: s.string('The id of the light'),
        },
      }),
      exposeComponent(CardComponent, {
        name: 'card',
        description: 'Show a card to the user',
        children: 'any',
        props: {
          title: s.streaming.string('The title of the card'),
        },
      }),
    ],
    tools: [
      createTool({
        name: 'getUser',
        description: 'Get information about the current user',
        handler: () => {
          const authService = inject(AuthService);
          return authService.getUser();
        },
      }),
      createTool({
        name: 'getLights',
        description: 'Get the current lights',
        handler: async () => this.lightsStore.entities(),
      }),
      createToolWithArgs({
        name: 'controlLight',
        description: 'Control a light',
        schema: s.object('Control light input', {
          lightId: s.string('The id of the light'),
          brightness: s.number('The brightness of the light'),
        }),
        handler: async (input) =>
          this.lightsStore.updateLight(input.lightId, {
            brightness: input.brightness,
          }),
      }),
    ],
  });

  lightsResource = resource({
    loader: () => {
      const lights = this.lightsStore.entities();
      return Promise.resolve(lights);
    },
  });

  onChange(args: { id: string; changes: Partial<Light> }) {
    this.lightsStore.updateLight(args.id, args.changes);
  }

  sendMessage(message: string) {
    this.chat.sendMessage({ role: 'user', content: message });
  }
}

// samples/smart-home/client-react/src/app/app.tsx
// Uncomment this line to use CSS modules
// import styles from './app.module.css';
import {
  ChatProvider,
  createTool,
  createToolWithArgs,
  s,
} from '@hashbrownai/react';
import { Link, Route, Routes } from 'react-router-dom';
import { StoreInitializer } from './components/StoreInitializer';
import { ChatPanel } from './shared/ChatPanel';
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from './shared/navigation-menu';
import { Toaster } from './shared/toaster';
import { useToast } from './shared/use-toast';
import { useSmartHomeStore } from './store/smart-home.store';
import { LightsView } from './views/LightsView';
import { ScenesView } from './views/ScenesView';
import { ScheduledScenesView } from './views/ScheduledScenesView';

export function App() {
  const { toast } = useToast();
  const lights = useSmartHomeStore((state) => state.lights);
  const updateLight = useSmartHomeStore((state) => state.updateLight);
  const scenes = useSmartHomeStore((state) => state.scenes);
  const scheduledScenes = useSmartHomeStore((state) => state.scheduledScenes);

  return (
    <ChatProvider
      endpoint={{
        url: 'http://localhost:3000/chat',
      }}
      model="gpt-4o-mini"
      messages={[
        {
          role: 'system',
          content:
            'You are a helpful assistant that can answer questions and help with tasks.',
        },
      ]}
      temperature={0.5}
      tools={[
        createTool({
          name: 'getLights',
          description: 'Get the current lights',
          handler: () => Promise.resolve(lights),
        }),
        createToolWithArgs({
          name: 'controlLight',
          description:
            'Control the light. Brightness is a number between 0 and 100.',
          schema: s.object('Control light input', {
            lightId: s.string('The id of the light'),
            brightness: s.number(
              'The brightness of the light, between 0 and 100',
            ),
          }),
          handler: (input) => {
            updateLight(input.lightId, { brightness: input.brightness });
            return Promise.resolve(true);
          },
        }),
      ]}
      maxTokens={1000}
    >
      <StoreInitializer />
      <div className="flex justify-between py-2 items-center border-b">
        <p className="text-xl font-bold p-2">Smart Home</p>
        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link to="/lights" className={navigationMenuTriggerStyle()}>
                  Lights
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link to="/scenes" className={navigationMenuTriggerStyle()}>
                  Scenes
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink asChild>
                <Link
                  to="/scheduled-scenes"
                  className={navigationMenuTriggerStyle()}
                >
                  Scheduled Scenes
                </Link>
              </NavigationMenuLink>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
      </div>
      <div className="grid grid-cols-4 gap-4">
        <div className="col-span-3">
          <div className="p-2">
            <Routes>
              <Route path="/lights" element={<LightsView lights={lights} />} />
              <Route path="/scenes" element={<ScenesView scenes={scenes} />} />
              <Route
                path="/scheduled-scenes"
                element={
                  <ScheduledScenesView scheduledScenes={scheduledScenes} />
                }
              />
              <Route path="/" element={<p>Home</p>} />
            </Routes>
          </div>
          {/* END: routes */}
        </div>
        <div className="col-span-1 border-l p-2">
          <ChatPanel />
        </div>
      </div>
      <Toaster />
    </ChatProvider>
  );
}

export default App;
