// packages/angular/src/utils/expose-component.fn.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { reflectComponentType } from '@angular/core';
import { s, ɵtypes, ɵui } from '@hashbrownai/core';

/**
 * @public
 */
export type AngularSignalLike<T> = () => T;

/**
 * @public
 */
export type ComponentPropSchema<T> = ɵtypes.Prettify<
  T extends { new (...args: any[]): infer P }
    ? {
        [K in keyof P]?: P[K] extends AngularSignalLike<infer U>
          ? s.Schema<U> | s.StandardJSONSchemaV1<U, U>
          : s.Schema<P[K]> | s.StandardJSONSchemaV1<P[K], P[K]>;
      }
    : never
>;

/**
 * @public
 */
export interface ExposedComponent<T extends { new (...args: any[]): any }> {
  component: T;
  fallback?: { new (...args: any[]): ɵui.ComponentFallbackProps };
  name: string;
  description: string;
  children?: 'any' | 'text' | ExposedComponent<any>[] | false;
  props?: ComponentPropSchema<T>;
}

/**
 * Exposes a component by combining it with additional configuration details.
 *
 * @public
 * @typeParam T - The type of the Angular component.
 * @param component - The Angular component to be exposed.
 * @param config - The configuration object for the component, excluding the component itself.
 * @returns An object representing the exposed component, including the component and its configuration.
 */
export function exposeComponent<T extends { new (...args: any[]): any }>(
  component: T,
  config: ɵtypes.Prettify<
    Omit<ExposedComponent<T>, 'component' | 'name' | 'props'> & {
      input?: ComponentPropSchema<T>;
      name?: string;
    }
  >,
): ExposedComponent<T> {
  const reflected = reflectComponentType(component);

  if (!reflected?.selector) {
    throw new Error(`Could not reflect component: ${component}`);
  }

  const { input, name, ...rest } = config;

  return {
    component,
    ...rest,
    props: input,
    name: name ?? reflected?.selector,
  };
}

// packages/react/src/expose-component.fn.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { s, ɵtypes, ɵui } from '@hashbrownai/core';
import type { ComponentType } from 'react';

/**
 * When exposing a component to the chat, you must provide a schema for the props of that component.
 * The `ComponentPropSchema` type defines the schema for those component props.
 *
 * @public
 * @example
 * ```ts
 * // Example usage in a tool definition.
 * exposeComponent(CardComponent, {
 *   // ...
 *   props: { // The ComponentPropSchema
 *     title: s.string('The title of the card'),
 *     description: s.streaming.string('The description of the card'),
 *   },
 * });
 * ```
 */
export type ComponentPropSchema<T> = ɵtypes.Prettify<
  T extends ComponentType<infer P>
    ? {
        [K in keyof P]?: s.Schema<P[K]> | s.StandardJSONSchemaV1<P[K], P[K]>;
      }
    : never
>;

/**
 * This type defines the configuration for a component to be exposed to the chat.
 *
 * @public
 * @example
 * ```ts
 * exposeComponent(CardComponent, {
 *   name: 'CardComponent',
 *   description: 'Show a card with children components to the user',
 *   children: 'any',
 *   props: {
 *     title: s.string('The title of the card'),
 *     description: s.streaming.string('The description of the card'),
 *   },
 * });
 * ```
 */
export interface ExposedComponent<T extends ComponentType<any>> {
  /**
   * The component to be exposed.
   */
  component: T;
  /**
   * Optional fallback component rendered while props are streaming.
   */
  fallback?: ComponentType<ɵui.ComponentFallbackProps>;
  /**
   * The name of the component.
   */
  name: string;
  /**
   * The description of the component.  This is also used by the LLM to understand when to use the component.
   */
  description: string;
  /**
   * The children of the component.
   */
  children?: 'any' | 'text' | ExposedComponent<any>[] | false;
  /**
   * The schema describing the props for this component.
   */
  props?: ComponentPropSchema<T>;
}

/**
 * Creates an object used to expose a component for use by the LLM.
 *
 * @example
 * ```ts
 * exposeComponent(
 *   CardComponent, // The React component to be exposed.
 *   { // The exposed component configuration.
 *     name: 'CardComponent',
 *     description: 'Show a card with children components to the user',
 *     children: 'any',
 *     props: {
 *       title: s.string('The title of the card'),
 *       description: s.streaming.string('The description of the card'),
 *     },
 *   },
 * });
 * ```
 *
 * @returns An object representing the component in order to expose it to the LLM.
 * @public
 */
export function exposeComponent<T extends ComponentType<any>>(
  /**
   * The component to be exposed.
   */
  component: T,
  /**
   * The configuration object for the component, excluding the component itself.
   */
  config: ɵtypes.Prettify<Omit<ExposedComponent<T>, 'component'>>,
): ExposedComponent<T> {
  return {
    component,
    ...config,
  };
}
