// samples/langchain/next/src/app/langgraph/page.tsx
'use client';

import { prompt, s } from '@hashbrownai/core';
import { useTool, useUiChat, useUiCompletion } from '@hashbrownai/react';
import { HumanMessage, Message } from '@langchain/langgraph-sdk';
import { useStream } from '@langchain/langgraph-sdk/react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Chat from '../../components/chat/Chat';
import { Step } from '../../components/chat/Steps';
import InfiniteLoader from '../../components/layout/InfiniteLoader';
import { useStableObject } from '../../hooks/use-stable-object';
import { exposedHeading } from '../../ui/Heading';
import { exposedOrderedList } from '../../ui/OrderedList';
import { exposedParagraph } from '../../ui/Paragraph';
import { exposedUnorderedList } from '../../ui/UnorderedList';
import { exposedWeather } from '../../ui/Weather';
import styles from './page.module.css';

export default function LangGraphPage() {
  const [threadId, setThreadId] = useState<string | null>(null);
  const stream = useStream<{ messages: Message[]; steps: Step[] }>({
    assistantId: 'plan',
    apiUrl: 'http://localhost:2024',
    threadId,
    onThreadId: setThreadId,
    reconnectOnMount: () => window.localStorage,
  });
  const retrievalValue = useMemo(() => {
    if (stream.isLoading || stream.isThreadLoading) {
      return null;
    }
    return stream.values;
  }, [stream.isLoading, stream.isThreadLoading, stream.values]);
  const retrieval = useStableObject(retrievalValue);

  useEffect(() => {
    console.log('retrieval', retrieval);
  }, [retrieval]);

  const updatePlanTool = useTool({
    name: 'update_plan',
    description: "Update the plan with the user's query.",
    handler: async (input: { query: string }, abortSignal: AbortSignal) => {
      if (abortSignal.aborted) {
        throw new Error('Plan agent request was aborted');
      }

      const message: HumanMessage = {
        type: 'human',
        content: input.query,
      };

      const onAbort = () => {
        void stream.stop();
      };
      abortSignal.addEventListener('abort', onAbort);

      try {
        await stream.submit({
          messages: [message],
        });
      } finally {
        abortSignal.removeEventListener('abort', onAbort);
      }
    },
    deps: [stream],
    schema: s.object('Plan agent input', {
      query: s.string("The user's query to update the plan"),
    }),
  });

  const readPlanTool = useTool({
    name: 'read_plan',
    description: 'Read the current state of the plan',
    handler: async () => {
      return retrieval;
    },
    deps: [retrieval],
  });

  const collaboratePlanAgent = useUiChat({
    model: 'gpt-5-chat-latest',
    debugName: 'collaborate-plan-agent',
    system: prompt`
      You are a pilot agent and flight planning expert.

      **Instructions**

      You must first call the "update_plan" tool and provide the agent with the user's query.
      Use the "read_plan" tool to read the current state of the remote agent.
      
      **Examples**

      <user>What is the weather at KBDN?</user>
      <assistant>
        <tool-call>update_plan</tool-call>
      </assistant>
      <assistant>
        <ui>
          <h level="2" text="The current conditions at KBDN" />
          <p text="METAR and TAF details and key weather information" citations=${[]} />
        </ui>
      </assistant>
    `,
    tools: [updatePlanTool, readPlanTool],
    components: [
      exposedHeading,
      exposedParagraph,
      exposedOrderedList,
      exposedUnorderedList,
    ],
  });

  const renderPlanAgent = useUiCompletion({
    model: 'gpt-5.1',
    debugName: 'render-plan-agent',
    input: retrieval,
    system: prompt`
      You render the plan user interface using the available components.

      Examples

      <user>What is the weather at KBDN?</user>
      <assistant>
        <ui>
          <Weather icao="KBDN" metar="KBDN 123456 123456 123456" taf="KBDN 123456 123456 123456" ceilingFt=${10000} visibilitySm=${10} summary="Sunny" windDirectionDeg=${270} windSpeedKt=${15} temperatureC=${22} dewpointC=${18} altimeterInHg=${29.92} />
        </ui>
      </assistant>

      The examples above are only for reference. You must not use them in your response.
    `,
    components: [exposedWeather],
  });

  const onStop = useCallback(() => {
    void stream.stop();
  }, [stream.stop]);

  const rendering = useMemo(() => {
    return (
      collaboratePlanAgent.isRunningToolCalls ||
      renderPlanAgent.isSending ||
      renderPlanAgent.isReceiving
    );
  }, [
    collaboratePlanAgent.isRunningToolCalls,
    renderPlanAgent.isSending,
    renderPlanAgent.isReceiving,
  ]);

  const isRunning = useMemo(() => {
    return (
      stream.isLoading ||
      stream.isThreadLoading ||
      collaboratePlanAgent.isRunningToolCalls ||
      collaboratePlanAgent.isSending ||
      collaboratePlanAgent.isReceiving
    );
  }, [
    collaboratePlanAgent.isReceiving,
    collaboratePlanAgent.isRunningToolCalls,
    collaboratePlanAgent.isSending,
    stream.isLoading,
    stream.isThreadLoading,
  ]);

  return (
    <main className={styles.main}>
      <section className={styles.ui}>
        {rendering ? <InfiniteLoader /> : renderPlanAgent.ui}
      </section>
      <section className={styles.chat}>
        <Chat
          agent={collaboratePlanAgent}
          isRunning={isRunning}
          onStop={onStop}
          remoteAgentIsRunning={stream.isLoading || stream.isThreadLoading}
          remoteAgentSteps={stream.values?.steps ?? []}
          remoteAgentMessages={stream.values?.messages ?? []}
        />
      </section>
    </main>
  );
}

// samples/langchain/angular/src/app/langgraph/langgraph.component.ts
import { Component, computed, inject } from '@angular/core';
import {
  createTool,
  RenderMessageComponent,
  uiChatResource,
  uiCompletionResource,
} from '@hashbrownai/angular';
import { prompt, s } from '@hashbrownai/core';
import { type HumanMessage } from '@langchain/langgraph-sdk';
import { ChatComponent } from '../components/chat/chat.component';
import { InfiniteLoaderComponent } from '../components/layout/infinite-loader.component';
import { LanggraphService } from '../services/langgraph.service';
import {
  exposedHeading,
  exposedOrderedList,
  exposedParagraph,
  exposedUnorderedList,
  exposedWeather,
} from '../ui';

@Component({
  imports: [ChatComponent, InfiniteLoaderComponent, RenderMessageComponent],
  template: `
    <section class="ui">
      @if (rendering()) {
        <app-infinite-loader />
      } @else if (renderPlanAgent.value(); as uiMessage) {
        <hb-render-message [message]="uiMessage" />
      }
    </section>
    <section class="chat">
      <app-chat
        [agent]="collaboratePlanAgent"
        [isRunning]="isRunning()"
        (stopped)="onStop()"
        [remoteAgentIsRunning]="
          service.isLoading() || service.isThreadLoading()
        "
        [remoteAgentSteps]="service.steps()"
      />
    </section>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      height: 100%;
    }

    .ui {
      height: 100%;
      flex: 1 auto;
      min-width: 0;
      display: flex;
      flex-direction: column;
      align-items: stretch;
      padding: 16px;
      overflow: hidden;
    }

    .chat {
      height: 100%;
      display: flex;
      flex-direction: column;
      padding: 16px;
    }

    @media (min-width: 768px) {
      :host {
        flex-direction: row;
      }

      .chat {
        width: 420px;
        flex-shrink: 0;
      }
    }
  `,
})
export class LanggraphComponent {
  protected readonly service = inject(LanggraphService);

  private readonly retrieval = computed(() => {
    if (this.service.isLoading() || this.service.isThreadLoading()) {
      return null;
    }
    return {
      messages: this.service.messages(),
      steps: this.service.steps(),
    };
  });

  readonly updatePlanTool = createTool({
    name: 'update_plan',
    description: "Update the plan with the user's query.",
    schema: s.object('Plan agent input', {
      query: s.string("The user's query to update the plan"),
    }),
    handler: async (input: { query: string }, abortSignal: AbortSignal) => {
      if (abortSignal.aborted) {
        throw new Error('Plan agent request was aborted');
      }

      const message: HumanMessage = {
        type: 'human',
        content: input.query,
      };

      const onAbort = () => this.service.stop();
      abortSignal.addEventListener('abort', onAbort);

      try {
        await this.service.submit({
          messages: [message],
        });
      } finally {
        abortSignal.removeEventListener('abort', onAbort);
      }
    },
  });

  readonly readPlanTool = createTool({
    name: 'read_plan',
    description: 'Read the current state of the plan',
    handler: async () => {
      return this.retrieval();
    },
  });

  readonly collaboratePlanAgent = uiChatResource({
    model: 'gpt-5-chat-latest',
    debugName: 'collaborate-plan-agent',
    system: prompt`
      You are a pilot agent and flight planning expert.

      **Instructions**

      You must first call the "update_plan" tool and provide the agent with the user's query.
      Use the "read_plan" tool to read the current state of the remote agent.
      
      **Examples**

      <user>What is the weather at KBDN?</user>
      <assistant>
        <tool-call>update_plan</tool-call>
      </assistant>
      <assistant>
        <ui>
          <h level="2" text="The current conditions at KBDN" />
          <p text="METAR and TAF details and key weather information" />
        </ui>
      </assistant>
    `,
    tools: [this.updatePlanTool, this.readPlanTool],
    components: [
      exposedHeading,
      exposedParagraph,
      exposedOrderedList,
      exposedUnorderedList,
    ],
  });

  readonly renderPlanAgent = uiCompletionResource({
    model: 'gpt-5.1',
    debugName: 'render-plan-agent',
    input: this.retrieval,
    system: prompt`
      You render the plan user interface using the available components.

      Examples

      <user>What is the weather at KBDN?</user>
      <assistant>
        <ui>
          <Weather icao="KBDN" metar="KBDN 123456 123456 123456" taf="KBDN 123456 123456 123456" ceilingFt=${10000} visibilitySm=${10} summary="Sunny" windDirectionDeg=${270} windSpeedKt=${15} temperatureC=${22} dewpointC=${18} altimeterInHg=${29.92} />
        </ui>
      </assistant>

      The examples above are only for reference. You must not use them in your response.
    `,
    components: [exposedWeather],
  });

  readonly rendering = computed(() => {
    return (
      this.collaboratePlanAgent.isLoading() || this.renderPlanAgent.isLoading()
    );
  });

  readonly isRunning = computed(() => {
    return (
      this.service.isLoading() ||
      this.service.isThreadLoading() ||
      this.collaboratePlanAgent.isLoading()
    );
  });

  protected onStop(): void {
    this.service.stop();
    this.collaboratePlanAgent.stop(true);
  }
}
