// samples/langchain/next/src/ui/OrderedList.tsx
import { s } from '@hashbrownai/core';
import { exposeComponent } from '@hashbrownai/react';
import MagicTextRenderer from '../components/chat/MagicTextRenderer';
import styles from './OrderedList.module.css';

type OrderedListProps = {
  items: string[];
  citations: Array<{ id: number; url: string }> | null;
};

function OrderedList({ items }: OrderedListProps) {
  return (
    <div className={styles.wrapper}>
      <ol className={styles.list}>
        {items.map((text, index) => (
          <li key={index} className={styles.item}>
            <MagicTextRenderer text={text} />
          </li>
        ))}
      </ol>
    </div>
  );
}

OrderedList.displayName = 'OrderedList';

const exposedOrderedList = exposeComponent(OrderedList, {
  name: 'ol',
  description: 'Display a numbered list of text items',
  props: {
    items: s.streaming.array(
      'The ordered list entries',
      s.streaming.string('The content of a single list entry'),
    ),
    citations: s.anyOf([
      s.streaming.array(
        'Citation references shared across the list',
        s.object('A citation reference', {
          id: s.number('The number of the citation'),
          url: s.string('The URL of the citation'),
        }),
      ),
      s.nullish(),
    ]),
  },
});

export default OrderedList;
export { exposedOrderedList };

// samples/langchain/angular/src/app/ui/ordered-list.component.ts
import { Component, input } from '@angular/core';
import { exposeComponent, MagicText } from '@hashbrownai/angular';
import { s } from '@hashbrownai/core';

@Component({
  selector: 'app-ordered-list',
  imports: [MagicText],
  template: `
    <div class="wrapper">
      <ol class="list">
        @for (item of items(); track $index) {
          <li class="item">
            <hb-magic-text [text]="item" />
          </li>
        }
      </ol>
    </div>
  `,
  styles: `
    .wrapper {
      display: block;
      width: var(--article-width, 100%);
      margin: 12px 0;
    }

    .list {
      margin: 0;
      padding-left: 24px;
      display: flex;
      flex-direction: column;
      gap: 4px;
      list-style-type: decimal;
    }

    .item {
      line-height: 1.3;
    }
  `,
})
export class OrderedListComponent {
  readonly items = input.required<string[]>();
}

export const exposedOrderedList = exposeComponent(OrderedListComponent, {
  name: 'ol',
  description: 'Display a numbered list of text items',
  input: {
    items: s.streaming.array(
      'The ordered list entries',
      s.streaming.string('The content of a single list entry'),
    ),
  },
});
