// demo/src/app/features/chat/chat-panel.component.ts
import { Component, inject } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { Store } from '@ngrx/store';
import {
  createTool,
  createToolWithArgs,
  exposeComponent,
  richChatResource,
} from '@cassini/core';
import { tap } from 'rxjs';
import { AuthService } from '../../shared/auth.service';
import { SmartHomeService } from '../../services/smart-home.service';
import { ChatActions } from './actions';
import { MessagesComponent } from './components/messages.component';
import { ComposerComponent } from './components/composer.component';
import { ChatAiActions } from './actions/chat-ai.actions';
import { LightCardComponent } from './components/light-card.component';
import { s } from '@cassini/core';

@Component({
  selector: 'app-chat-panel',
  standalone: true,
  imports: [
    MatIconModule,
    MatButtonModule,
    ComposerComponent,
    MessagesComponent,
  ],
  template: `
    <div class="chat-header">
      <h3>Chat</h3>

      <button
        mat-icon-button
        aria-label="Close chat panel"
        (click)="closePanel()"
      >
        <mat-icon>close</mat-icon>
      </button>
    </div>

    <div class="chat-messages">
      <app-chat-messages
        [messages]="chat.value()"
        [components]="components"
      ></app-chat-messages>
    </div>

    <div class="chat-composer">
      <app-chat-composer
        (sendMessage)="chat.sendMessage({ role: 'user', content: $event })"
      ></app-chat-composer>
    </div>
  `,
  styles: [
    `
      :host {
        display: grid;
        position: fixed;
        top: 64px;
        bottom: 0;
        right: 0;
        width: 400px;
        height: calc(100vh - 64px);
        background-color: var(--mat-sys-surface);
        border-left: 1px solid rgba(255, 255, 255, 0.12);
        grid-template-areas:
          'header'
          'messages'
          'composer';
        grid-template-rows: auto 1fr auto;
        grid-template-columns: 1fr;
      }

      .chat-header {
        grid-area: header;
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 16px;
        border-bottom: 1px solid rgba(255, 255, 255, 0.12);
      }

      .chat-messages {
        grid-area: messages;
      }

      .chat-composer {
        grid-area: composer;
        padding: 16px;
      }
    `,
  ],
})
export class ChatPanelComponent {
  store = inject(Store);
  authService = inject(AuthService);
  smartHomeService = inject(SmartHomeService);

  components = {
    light: LightCardComponent,
  };

  chat = richChatResource({
    model: 'gpt-4o',
    messages: [
      {
        role: 'system',
        content:
          'You are a helpful assistant that can answer questions and help with tasks.',
      },
    ],
    components: [
      exposeComponent({
        name: 'light',
        description: 'Show a light to the user',
        component: LightCardComponent,
        inputs: {
          lightId: s.string('The id of the light'),
        },
      }),
    ],
    tools: [
      createTool({
        name: 'getUser',
        description: 'Get information about the current user',
        handler: () => {
          const auth = inject(AuthService);

          return auth.getUser();
        },
      }),
      createTool({
        name: 'getLights',
        description: 'Get the current lights',
        handler: () => this.smartHomeService.loadLights(),
      }),
      createToolWithArgs({
        name: 'controlLight',
        description:
          'Control the light. Brightness is a number between 0 and 100.',
        schema: s.object('Control light input', {
          lightId: s.string('The id of the light'),
          brightness: s.number(
            'The brightness of the light, between 0 and 100'
          ),
        }),
        handler: (input) => {
          return this.smartHomeService
            .controlLight(input.lightId, input.brightness)
            .pipe(
              tap((light) =>
                this.store.dispatch(
                  ChatAiActions.controlLight({
                    lightId: light.id,
                    brightness: light.brightness,
                  })
                )
              )
            );
        },
      }),
    ],
  });

  closePanel() {
    this.store.dispatch(ChatActions.closeChatPanel());
  }
}

// samples/smart-home/client-react/src/app/shared/ChatPanel.tsx
import { Chat, s } from '@hashbrownai/core';
import { createTool, createToolWithArgs, useChat } from '@hashbrownai/react';
import { useEffect, useRef, useState } from 'react';
import { useSmartHomeStore } from '../store/smart-home.store';
import { Button } from './button';
import { Message } from './Message';
import { ScrollArea } from './scrollarea';
import { Textarea } from './textarea';

export const ChatPanel = () => {
  // const { messages, sendMessage, isThinking, stop } = useRichChat({
  //   predictionPrompt:
  //     'You are a helpful assistant that can answer questions and help with tasks.',
  //   components: [
  //     exposeComponent(
  //       'Light',
  //       'A component that lets you configure and control a light.',
  //       Light,
  //       {
  //         lightId: s.string('The id of the light'),
  //       },
  //     ),
  //   ],
  //   tools: [
  //     createTool({
  //       name: 'getLights',
  //       description: 'Get the current lights',
  //       handler: () => Promise.resolve(lights),
  //     }),
  //     createToolWithArgs({
  //       name: 'controlLight',
  //       description:
  //         'Control the light. Brightness is a number between 0 and 100.',
  //       schema: s.object('Control light input', {
  //         lightId: s.string('The id of the light'),
  //         brightness: s.number(
  //           'The brightness of the light, between 0 and 100',
  //         ),
  //       }),
  //       handler: (input) => {
  //         updateLight(input.lightId, { brightness: input.brightness });
  //         return Promise.resolve(true);
  //       },
  //     }),
  //   ],
  // });

  const { messages, sendMessage, isThinking, stop } = useChat({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content:
          'You are a helpful assistant that can answer questions and help with tasks.',
      },
    ],
    temperature: 0.5,
    tools: [
      createTool({
        name: 'getLights',
        description: 'Get the current lights',
        handler: () => Promise.resolve(useSmartHomeStore.getState().lights),
      }),
      createToolWithArgs({
        name: 'controlLight',
        description:
          'Control the light. Brightness is a number between 0 and 100.',
        schema: s.object('Control light input', {
          lightId: s.string('The id of the light'),
          brightness: s.number(
            'The brightness of the light, between 0 and 100',
          ),
        }),
        handler: (input) => {
          useSmartHomeStore.getState().updateLight(input.lightId, {
            brightness: input.brightness,
          });
          return Promise.resolve(true);
        },
      }),
    ],
    maxTokens: 1000,
  });

  const scrollAreaRef = useRef<HTMLDivElement>(null);

  // Add state for the textarea input
  const [inputValue, setInputValue] = useState('');

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    if (scrollAreaRef.current) {
      const scrollContainer = scrollAreaRef.current.querySelector(
        '[data-radix-scroll-area-viewport]',
      );
      if (scrollContainer) {
        scrollContainer.scrollTop = scrollContainer.scrollHeight;
      }
    }
  }, [messages]);

  const onSubmit = () => {
    // Only submit if there's text
    if (!inputValue.trim()) return;

    // Add the user message to the messages list
    const newUserMessage: Chat.Message = {
      role: 'user',
      content: inputValue,
    };

    setInputValue('');

    sendMessage(newUserMessage);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    // Submit on Enter (but not on Shift+Enter)
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault(); // Prevent default behavior (new line)
      if (isThinking) {
        stop();
      } else {
        onSubmit();
      }
    }
  };

  return (
    <div className="flex flex-col">
      <div className="flex flex-col py-2">
        <ScrollArea className="h-[600px]" ref={scrollAreaRef}>
          <div className="flex flex-col gap-2">
            {messages.map((message, index) => (
              <Message key={index} message={message} />
            ))}
          </div>
        </ScrollArea>
      </div>
      <div className="flex flex-col text-sm text-foreground/50 gap-2 h-6 justify-end">
        {isThinking && <p>Thinking...</p>}
      </div>
      <div className="flex flex-col gap-2">
        <Textarea
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Type your message..."
        />
        {!isThinking ? (
          <Button onClick={onSubmit}>Send</Button>
        ) : (
          <Button variant="outline" onClick={stop}>
            Stop
          </Button>
        )}
      </div>
    </div>
  );
};
