// tools/runtime-smoke/react/src/structured-smoke.tsx
import { s } from '@hashbrownai/core';
import { useStructuredChat } from '@hashbrownai/react';
import { useState } from 'react';

const answerSchema = s.object('Runtime smoke answer', {
  answer: s.streaming.string('Answer text'),
  count: s.number('Result count'),
});

function readRetries(): number {
  const value = Number.parseInt(
    new URL(globalThis.location.href).searchParams.get('retries') ?? '0',
    10,
  );

  return Math.min(1, Math.max(0, Number.isNaN(value) ? 0 : value));
}

function errorText(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }

  return error === undefined ? '' : String(error);
}

/** React structured chat fixture used by the shared runtime smoke scenario. */
export function StructuredSmoke() {
  const [prompt, setPrompt] = useState('');
  const [submitted, setSubmitted] = useState('');
  const {
    error,
    generatingError,
    isLoading,
    lastAssistantMessage,
    sendMessage,
    sendingError,
    stop,
  } = useStructuredChat({
    model: 'gpt-4o',
    system: 'Runtime smoke system prompt.',
    schema: answerSchema,
    retries: readRetries(),
  });
  const answer = lastAssistantMessage?.content?.answer ?? '';
  const count = lastAssistantMessage?.content?.count ?? '';

  function send() {
    setSubmitted(prompt);
    sendMessage({ role: 'user', content: prompt });
  }

  return (
    <section>
      <input
        data-testid="prompt"
        value={prompt}
        onChange={(event) => setPrompt(event.currentTarget.value)}
      />
      <button data-testid="send" type="button" onClick={send}>
        Send
      </button>
      <button data-testid="stop" type="button" onClick={() => stop()}>
        Stop
      </button>
      <div data-testid="status">{isLoading ? 'loading' : 'idle'}</div>
      <div data-testid="user-message">{submitted}</div>
      <div data-testid="assistant"></div>
      <div data-testid="error">{errorText(error)}</div>
      <div data-testid="sending-error">{errorText(sendingError)}</div>
      <div data-testid="generating-error">{errorText(generatingError)}</div>
      <div data-testid="tool-count">0</div>
      <div data-testid="structured-answer">{answer}</div>
      <div data-testid="structured-count">{count}</div>
    </section>
  );
}

// tools/runtime-smoke/angular/src/app/structured-smoke.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  signal,
} from '@angular/core';
import { structuredChatResource } from '@hashbrownai/angular';
import { s } from '@hashbrownai/core';

const answerSchema = s.object('Runtime smoke answer', {
  answer: s.streaming.string('Answer text'),
  count: s.number('Result count'),
});

function readRetries(): number {
  const value = Number.parseInt(
    new URL(globalThis.location.href).searchParams.get('retries') ?? '0',
    10,
  );

  return Math.min(1, Math.max(0, Number.isNaN(value) ? 0 : value));
}

function errorText(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }

  return error === undefined ? '' : String(error);
}

/** Angular structured chat fixture used by the shared runtime smoke scenario. */
@Component({
  selector: 'runtime-structured-smoke',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section>
      <input
        data-testid="prompt"
        [value]="prompt()"
        (input)="onPromptInput($event)"
      />
      <button data-testid="send" type="button" (click)="send()">Send</button>
      <button data-testid="stop" type="button" (click)="stop()">Stop</button>
      <div
        data-testid="status"
        [textContent]="chat.isLoading() ? 'loading' : 'idle'"
      ></div>
      <div data-testid="user-message" [textContent]="submitted()"></div>
      <div data-testid="assistant"></div>
      <div data-testid="error" [textContent]="toErrorText(chat.error())"></div>
      <div
        data-testid="sending-error"
        [textContent]="toErrorText(chat.sendingError())"
      ></div>
      <div
        data-testid="generating-error"
        [textContent]="toErrorText(chat.generatingError())"
      ></div>
      <div data-testid="tool-count">0</div>
      <div data-testid="structured-answer" [textContent]="answer()"></div>
      <div data-testid="structured-count" [textContent]="count()"></div>
    </section>
  `,
})
export class StructuredSmoke {
  protected readonly prompt = signal('');
  protected readonly submitted = signal('');
  protected readonly toErrorText = errorText;
  protected readonly chat = structuredChatResource({
    model: 'gpt-4o',
    system: 'Runtime smoke system prompt.',
    schema: answerSchema,
    retries: readRetries(),
  });
  protected readonly answer = computed(
    () => this.chat.lastAssistantMessage()?.content?.answer ?? '',
  );
  protected readonly count = computed(
    () => this.chat.lastAssistantMessage()?.content?.count ?? '',
  );

  protected onPromptInput(event: Event): void {
    this.prompt.set((event.currentTarget as HTMLInputElement).value);
  }

  protected send(): void {
    const content = this.prompt();
    this.submitted.set(content);
    this.chat.sendMessage({ role: 'user', content });
  }

  protected stop(): void {
    this.chat.stop();
  }
}
