// samples/smart-home/client-react/src/app/shared/ChatPanel.tsx
import { Chat, s } from '@hashbrownai/core';
import { createTool, createToolWithArgs, useChat } from '@hashbrownai/react';
import { useEffect, useRef, useState } from 'react';
import { useSmartHomeStore } from '../store/smart-home.store';
import { Button } from './button';
import { Message } from './Message';
import { ScrollArea } from './scrollarea';
import { Textarea } from './textarea';

export const ChatPanel = () => {
  // const { messages, sendMessage, isThinking, stop } = useRichChat({
  //   predictionPrompt:
  //     'You are a helpful assistant that can answer questions and help with tasks.',
  //   components: [
  //     exposeComponent(
  //       'Light',
  //       'A component that lets you configure and control a light.',
  //       Light,
  //       {
  //         lightId: s.string('The id of the light'),
  //       },
  //     ),
  //   ],
  //   tools: [
  //     createTool({
  //       name: 'getLights',
  //       description: 'Get the current lights',
  //       handler: () => Promise.resolve(lights),
  //     }),
  //     createToolWithArgs({
  //       name: 'controlLight',
  //       description:
  //         'Control the light. Brightness is a number between 0 and 100.',
  //       schema: s.object('Control light input', {
  //         lightId: s.string('The id of the light'),
  //         brightness: s.number(
  //           'The brightness of the light, between 0 and 100',
  //         ),
  //       }),
  //       handler: (input) => {
  //         updateLight(input.lightId, { brightness: input.brightness });
  //         return Promise.resolve(true);
  //       },
  //     }),
  //   ],
  // });

  const { messages, sendMessage, isThinking, stop } = useChat({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content:
          'You are a helpful assistant that can answer questions and help with tasks.',
      },
    ],
    temperature: 0.5,
    tools: [
      createTool({
        name: 'getLights',
        description: 'Get the current lights',
        handler: () => Promise.resolve(useSmartHomeStore.getState().lights),
      }),
      createToolWithArgs({
        name: 'controlLight',
        description:
          'Control the light. Brightness is a number between 0 and 100.',
        schema: s.object('Control light input', {
          lightId: s.string('The id of the light'),
          brightness: s.number(
            'The brightness of the light, between 0 and 100',
          ),
        }),
        handler: (input) => {
          useSmartHomeStore.getState().updateLight(input.lightId, {
            brightness: input.brightness,
          });
          return Promise.resolve(true);
        },
      }),
    ],
    maxTokens: 1000,
  });

  const scrollAreaRef = useRef<HTMLDivElement>(null);

  // Add state for the textarea input
  const [inputValue, setInputValue] = useState('');

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    if (scrollAreaRef.current) {
      const scrollContainer = scrollAreaRef.current.querySelector(
        '[data-radix-scroll-area-viewport]',
      );
      if (scrollContainer) {
        scrollContainer.scrollTop = scrollContainer.scrollHeight;
      }
    }
  }, [messages]);

  const onSubmit = () => {
    // Only submit if there's text
    if (!inputValue.trim()) return;

    // Add the user message to the messages list
    const newUserMessage: Chat.Message = {
      role: 'user',
      content: inputValue,
    };

    setInputValue('');

    sendMessage(newUserMessage);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    // Submit on Enter (but not on Shift+Enter)
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault(); // Prevent default behavior (new line)
      if (isThinking) {
        stop();
      } else {
        onSubmit();
      }
    }
  };

  return (
    <div className="flex flex-col">
      <div className="flex flex-col py-2">
        <ScrollArea className="h-[600px]" ref={scrollAreaRef}>
          <div className="flex flex-col gap-2">
            {messages.map((message, index) => (
              <Message key={index} message={message} />
            ))}
          </div>
        </ScrollArea>
      </div>
      <div className="flex flex-col text-sm text-foreground/50 gap-2 h-6 justify-end">
        {isThinking && <p>Thinking...</p>}
      </div>
      <div className="flex flex-col gap-2">
        <Textarea
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Type your message..."
        />
        {!isThinking ? (
          <Button onClick={onSubmit}>Send</Button>
        ) : (
          <Button variant="outline" onClick={stop}>
            Stop
          </Button>
        )}
      </div>
    </div>
  );
};

// samples/smart-home/client/src/app/features/chat/chat-panel.component.ts
import {
  Component,
  effect,
  ElementRef,
  inject,
  ViewChild,
} from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import {
  chatResource,
  createTool,
  createToolWithArgs,
  exposeComponent,
  uiChatResource,
} from '@hashbrownai/angular';
import { s } from '@hashbrownai/core';
import {
  createToolJavaScript,
  defineFunction,
} from '@hashbrownai/tool-javascript';
import { Store } from '@ngrx/store';
// import variant from '@jitl/quickjs-singlefile-browser-release-asyncify';
import variant from '@jitl/quickjs-singlefile-browser-debug-asyncify';
import { lastValueFrom, tap } from 'rxjs';
import { SmartHomeService } from '../../services/smart-home.service';
import { AuthService } from '../../shared/auth.service';
import { ChatAiActions } from './actions/chat-ai.actions';
import { CardComponent } from './components/card.component';
import { ComposerComponent } from './components/composer.component';
import { LightCardComponent } from './components/light-card.component';
import { MarkdownComponent } from './components/markdown.component';
import { MessagesComponent } from './components/messages.component';
import { SimpleMessagesComponent } from './components/simple-messages.component';

@Component({
  selector: 'app-chat-panel',
  standalone: true,
  imports: [
    MatIconModule,
    MatButtonModule,
    ComposerComponent,
    MessagesComponent,
    SimpleMessagesComponent,
  ],
  template: `
    <div class="chat-header">
      <h3>Chat</h3>
    </div>

    <div #contentDiv class="chat-messages">
      @if (simpleDemo) {
        <app-simple-chat-messages [messages]="simpleChat.value()" />
      } @else {
        <app-chat-messages [messages]="chat.value()" />
      }
    </div>

    <div class="chat-composer">
      <app-chat-composer
        (sendMessage)="sendMessage($event)"
      ></app-chat-composer>
    </div>
  `,
  styles: [
    `
      :host {
        display: grid;
        position: fixed;
        top: 64px;
        bottom: 0;
        right: 0;
        width: 40%;
        height: calc(100vh - 64px);
        background-color: var(--mat-sys-surface);
        border-left: 1px solid rgba(255, 255, 255, 0.12);
        grid-template-areas:
          'header'
          'messages'
          'composer';
        grid-template-rows: auto 1fr auto;
        grid-template-columns: 1fr;
      }

      .chat-header {
        grid-area: header;
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 16px;
        border-bottom: 1px solid rgba(255, 255, 255, 0.12);
      }

      .chat-messages {
        grid-area: messages;
        flex-grow: 0;
        overflow-y: auto;
        display: flex;
        flex-direction: column;
        gap: 16px;
      }

      .chat-composer {
        grid-area: composer;
        padding: 16px;
      }
    `,
  ],
})
export class ChatPanelComponent {
  store = inject(Store);
  authService = inject(AuthService);
  smartHomeService = inject(SmartHomeService);

  simpleDemo = false;

  @ViewChild('contentDiv') private contentDiv: ElementRef = {} as ElementRef;

  constructor() {
    effect(() => {
      // React when messages change
      this.chat.value();
      if (this.contentDiv.nativeElement) {
        this.contentDiv.nativeElement.scrollTop =
          this.contentDiv.nativeElement.scrollHeight;
      }
    });
  }

  /**
   * --------------------------------------------------------------------------
   * Simple chat
   * --------------------------------------------------------------------------
   */
  simpleChat = chatResource({
    model: 'gpt-4.1',
    prompt: `You are a helpful assistant that can answer questions and help with tasks.`,
    tools: [
      createTool({
        name: 'getUser',
        description: 'Get information about the current user',
        handler: () => {
          const auth = inject(AuthService);

          return auth.getUser();
        },
      }),
      createTool({
        name: 'getLights',
        description: 'Get the current lights',
        handler: () => lastValueFrom(this.smartHomeService.loadLights()),
      }),
      createToolWithArgs({
        name: 'controlLight',
        description: 'Control a light',
        schema: s.object('Control light input', {
          lightId: s.string('The id of the light'),
          brightness: s.number('The brightness of the light'),
        }),
        handler: (input) =>
          lastValueFrom(
            this.smartHomeService
              .controlLight(input.lightId, input.brightness)
              .pipe(
                tap((light) => {
                  this.store.dispatch(
                    ChatAiActions.controlLight({
                      lightId: light.id,
                      brightness: light.brightness,
                    }),
                  );
                }),
              ),
          ),
      }),
    ],
  });

  /**
   * --------------------------------------------------------------------------
   * UI chat
   * --------------------------------------------------------------------------
   */
  chat = uiChatResource({
    // model: 'gemini-2.5-pro-exp-03-25',
    model: 'gpt-4.1',
    prompt: `
      You are a helpful assistant that can answer questions and help with tasks.
    `,
    components: [
      exposeComponent(MarkdownComponent, {
        name: 'markdown',
        description: 'Show markdown to the user',
        props: {
          data: s.streaming.string('The markdown content'),
        },
      }),
      exposeComponent(LightCardComponent, {
        name: 'light',
        description: 'Show a light to the user',
        props: {
          lightId: s.string('The id of the light'),
        },
      }),
      exposeComponent(CardComponent, {
        name: 'card',
        description: 'Show a card to the user',
        children: 'any',
        props: {
          title: s.streaming.string('The title of the card'),
        },
      }),
    ],
    tools: [
      createTool({
        name: 'getUser',
        description: 'Get information about the current user',
        handler: () => this.authService.getUser(),
      }),
      // createTool({
      //   name: 'getLights',
      //   description: 'Get the current lights',
      //   handler: () => lastValueFrom(this.smartHomeService.loadLights()),
      // }),
      createToolWithArgs({
        name: 'controlLight',
        description: 'Control a light',
        schema: s.object('Control light input', {
          lightId: s.string('The id of the light'),
          brightness: s.number('The brightness of the light'),
        }),
        handler: (input) =>
          lastValueFrom(
            this.smartHomeService
              .controlLight(input.lightId, input.brightness)
              .pipe(
                tap((light) => {
                  this.store.dispatch(
                    ChatAiActions.controlLight({
                      lightId: light.id,
                      brightness: light.brightness,
                    }),
                  );
                }),
              ),
          ),
      }),
      createToolJavaScript({
        loadVariant: () => Promise.resolve(variant),
        functions: [
          defineFunction({
            name: 'getLights',
            description: 'Get the current lights',
            output: s.array(
              'The lights',
              s.object('A light', {
                id: s.string('The id of the light'),
                brightness: s.number('The brightness of the light'),
              }),
            ),
            handler: () => lastValueFrom(this.smartHomeService.loadLights()),
          }),
        ],
      }),
    ],
    debugName: 'ui-chat',
  });

  sendMessage(message: string) {
    if (this.simpleDemo) {
      this.simpleChat.sendMessage({ role: 'user', content: message });
    } else {
      this.chat.sendMessage({ role: 'user', content: message });
    }
  }
}
